services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: pg_isready -U postgres
      start_period: 40s
  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  websocket_client:
    build: ./websocket_client
    restart: always
    environment:
      WS_SERVER: ${WS_SERVER}
      CAMERA_IDS: ${CAMERA_IDS}
    depends_on:
      - redis
  alert_processor:
    build: ./alert_processor
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
volumes:
  db_data:
  redis_data:
